#!/usr/bin/env python3
"""Writes the Homebrew formula, Scoop manifest and winget manifests for one release.

    python3 packaging/render.py <version> <checksums-dir> <out-dir>

<checksums-dir> holds the release's `envbyte-<target>.<ext>.sha256` files. The
output mirrors where each file lives in its own repository:

    <out-dir>/homebrew/Formula/envbyte.rb           -> NYLONXD/homebrew-tap
    <out-dir>/scoop/bucket/envbyte.json             -> NYLONXD/scoop-bucket
    <out-dir>/winget/manifests/e/Envbyte/Envbyte/<version>/*.yaml
                                                    -> microsoft/winget-pkgs
"""

import json
import sys
from pathlib import Path

REPO = "NYLONXD/EnvByte_CLI"
HOMEPAGE = "https://envbyte.trackedge.in"
DESCRIPTION = "End-to-end encrypted .env sharing for teams"
WINDOWS_TARGET = "x86_64-pc-windows-msvc"


def main() -> None:
    if len(sys.argv) != 4:
        sys.exit(__doc__)
    version = sys.argv[1].removeprefix("v")
    checksums = Path(sys.argv[2])
    out = Path(sys.argv[3])
    base = f"https://github.com/{REPO}/releases/download/v{version}"

    def asset(target: str) -> tuple[str, str]:
        name = f"envbyte-{target}.{'zip' if target == WINDOWS_TARGET else 'tar.gz'}"
        digest = (checksums / f"{name}.sha256").read_text().split()[0].lower()
        if len(digest) != 64:
            sys.exit(f"bad checksum for {name}")
        return f"{base}/{name}", digest

    write(out / "homebrew" / "Formula" / "envbyte.rb", formula(version, asset))
    write(out / "scoop" / "bucket" / "envbyte.json", scoop(version, *asset(WINDOWS_TARGET)))
    for filename, text in winget(version, *asset(WINDOWS_TARGET)).items():
        write(out / "winget" / "manifests" / "e" / "Envbyte" / "Envbyte" / version / filename, text)


def formula(version: str, asset) -> str:
    def block(target: str) -> str:
        url, sha = asset(target)
        return f'      url "{url}"\n      sha256 "{sha}"'

    return f'''# Generated by packaging/render.py in {REPO}; edits here are overwritten.
class Envbyte < Formula
  desc "{DESCRIPTION}"
  homepage "{HOMEPAGE}"
  version "{version}"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    on_arm do
{block("aarch64-apple-darwin")}
    end
    on_intel do
{block("x86_64-apple-darwin")}
    end
  end

  on_linux do
    on_arm do
{block("aarch64-unknown-linux-gnu")}
    end
    on_intel do
{block("x86_64-unknown-linux-musl")}
    end
  end

  def install
    bin.install "envbyte"
  end

  test do
    assert_match version.to_s, shell_output("#{{bin}}/envbyte --version")
  end
end
'''


def scoop(version: str, url: str, sha: str) -> str:
    folder = f"envbyte-{WINDOWS_TARGET}"
    windows = {"url": url, "hash": sha, "extract_dir": folder}
    autoupdate = {
        "url": f"https://github.com/{REPO}/releases/download/v$version/{folder}.zip",
        "hash": {"url": "$url.sha256"},
        "extract_dir": folder,
    }
    manifest = {
        "version": version,
        "description": DESCRIPTION,
        "homepage": HOMEPAGE,
        "license": "MIT|Apache-2.0",
        # Windows on ARM runs the x64 build under emulation.
        "architecture": {"64bit": windows, "arm64": windows},
        "bin": "envbyte.exe",
        "checkver": {"github": f"https://github.com/{REPO}"},
        "autoupdate": {"architecture": {"64bit": autoupdate, "arm64": autoupdate}},
    }
    return json.dumps(manifest, indent=4) + "\n"


def winget(version: str, url: str, sha: str) -> dict[str, str]:
    def header(kind: str) -> str:
        return (
            f"# yaml-language-server: $schema=https://aka.ms/winget-manifest.{kind}.1.9.0.schema.json\n"
            f"PackageIdentifier: Envbyte.Envbyte\nPackageVersion: {version}\n"
        )

    schema = "ManifestVersion: 1.9.0\n"
    return {
        "Envbyte.Envbyte.yaml": header("version") + "DefaultLocale: en-US\nManifestType: version\n" + schema,
        "Envbyte.Envbyte.installer.yaml": header("installer")
        + f"""InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: envbyte-{WINDOWS_TARGET}\\envbyte.exe
    PortableCommandAlias: envbyte
Installers:
  - Architecture: x64
    InstallerUrl: {url}
    InstallerSha256: {sha.upper()}
ManifestType: installer
"""
        + schema,
        "Envbyte.Envbyte.locale.en-US.yaml": header("defaultLocale")
        + f"""PackageLocale: en-US
Publisher: Envbyte
PublisherUrl: {HOMEPAGE}
PublisherSupportUrl: https://github.com/{REPO}/issues
PackageName: Envbyte
PackageUrl: https://github.com/{REPO}
License: MIT OR Apache-2.0
LicenseUrl: https://github.com/{REPO}/blob/main/LICENSE-MIT
ShortDescription: {DESCRIPTION}.
Description: Envbyte encrypts .env files on your machine, seals the project key to each teammate's identity key, and keeps versioned history with rollback. The server only ever stores ciphertext.
Moniker: envbyte
Tags:
  - dotenv
  - secrets
  - encryption
  - cli
ReleaseNotesUrl: https://github.com/{REPO}/releases/tag/v{version}
ManifestType: defaultLocale
"""
        + schema,
    }


def write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {path}")


if __name__ == "__main__":
    main()
